name: Reusable workflow

on:
  workflow_call:
    inputs:
      reponame:
        required: true
        type: string

jobs:
  example_job:
    name: Run shared action and show passed value
    runs-on: ubuntu-latest
    steps:
      - name: pwd before checkout
        run: pwd
      - name: ls before checkout
        run: ls -a
      - uses: actions/checkout@v2
      - name: pwd after checkout
        run: pwd
      - name: ls after checkout
        run: ls -a
      - uses: ./.github/actions/shared
      - run: echo this workflow is run by ${{ inputs.reponame }}
