name: Reusable workflow

on:
  workflow_call:
    inputs:
      reponame:
        required: true
        type: string

jobs:
  example_job:
    name: Pass input to shared action
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls
      - uses: ./.github/actions/shared@main
      - run: echo this workflow is run by ${{ inputs.reponame }}
